### ISSUE TITLE
互star

### ISSUE THREAD

**Issue by bmxbmx3** [ouyangpeng/ChineseStrokeSorting#1]
大佬我看到你的项目有所启发，写了一个按拼音和笔顺排序的[cn_sort库](https://github.com/bmxbmx3/cn_sort)，望互star

**Comment by ouyangpeng** [comment]
> 大佬我看到你的项目有所启发，写了一个按拼音和笔顺排序的[cn_sort库](https://github.com/bmxbmx3/cn_sort)，望互star

写的很棒！已经star！

**Comment by bmxbmx3** [comment]
已经增加只按笔顺的排序方式：

```python
if __name__ == "__main__":
    a = list(sort_text_list(["二", "重要", "三", "一二", "一", "22", "1", "a", "重庆"], mode=Mode.bihua))
    print(a)

  # 2021-03-04 18:28:15,340 - all - INFO - handle_text_word函数运行时间为0.000000s
  # 2021-03-04 18:28:15,342 - all - INFO - sort_text_list函数运行时间为0.002019s
  # 2021-03-04 18:28:15,442 - all - INFO - get_word_dict函数运行时间为0.098080s
  # 2021-03-04 18:28:15,444 - all - INFO - radix_sort函数运行时间为0.000000s
  # ['1', '22', 'a', '一', '一二', '二', '三', '重庆', '重要']
```

**Comment by ouyangpeng** [comment]
> 已经增加只按笔顺的排序方式：
> 
> ```python
> if __name__ == "__main__":
>     a = list(sort_text_list(["二", "重要", "三", "一二", "一", "22", "1", "a", "重庆"], mode=Mode.bihua))
>     print(a)
> 
>   # 2021-03-04 18:28:15,340 - all - INFO - handle_text_word函数运行时间为0.000000s
>   # 2021-03-04 18:28:15,342 - all - INFO - sort_text_list函数运行时间为0.002019s
>   # 2021-03-04 18:28:15,442 - all - INFO - get_word_dict函数运行时间为0.098080s
>   # 2021-03-04 18:28:15,444 - all - INFO - radix_sort函数运行时间为0.000000s
>   # ['1', '22', 'a', '一', '一二', '二', '三', '重庆', '重要']
> ```

6666
